config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :products

  resources :users do
    resources :shopping_carts
  end

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name,:description,:quantity,:price, presence: true
  validates :name, uniqueness: true
  validates_numericality_of :quantity, :price , greater_than_or_equal_to: 0
  has_and_belongs_to_many :shopping_carts
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :shopping_cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if user_signed_in?
    @shopping_cart = ShoppingCart.find_or_create_by(user_id: current_user.id)
  end
    @products = Product.all
  end

  def show
    if user_signed_in?
      @shopping_cart = ShoppingCart.find_or_create_by(user_id: current_user.id)
    end
    @product = Product.find(params[:id])
  end

  def edit
    return redirect_to products_path unless user_signed_in? && current_user.admin

    @product = Product.find(params[:id])
  end

  def create
    return redirect_to products_path unless user_signed_in? && current_user.admin

    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def new
    return redirect_to products_path unless user_signed_in? && current_user.admin

    @product = Product.new
  end

  def update
    return redirect_to products_path unless user_signed_in? && current_user.admin

    @product = Product.find(params[:id])
    @product.assign_attributes(product_params)
    if @product.save
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    return redirect_to products_path unless user_signed_in? && current_user.admin

    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  # method to pull out product attributes
  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity)
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  def update
    product_id = params[:shopping_cart][:product_id]
    shopping_cart = current_user.shopping_cart
    if params[:shopping_cart][:remove]
    shopping_cart.products.delete(Product.find(product_id))
    else
    shopping_cart.products << (Product.find(product_id))
    end
    shopping_cart.save
    redirect_to products_path
  end
  def show
    shopping_cart = current_user.shopping_cart
    @products = shopping_cart.products
  end
  def edit
    @shopping_cart = current_user.shopping_cart
    @products = @shopping_cart.products
  end
  def destroy
    shopping_cart = current_user.shopping_cart
    shopping_cart.products.clear
    shopping_cart.save
    redirect_to edit_user_shopping_cart_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-72933903-2', 'auto');
    ga('send', 'pageview');

  </script>
</head>

<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid"><a href="/"><img class="house" src="https://d30y9cdsu7xlg0.cloudfront.net/png/41030-200.png"></a>
      <h1 style="display:inline"> Hipster Shop</h1>
        <div class="navbar-right middle">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
          <%= link_to "Shopping Cart", edit_user_shopping_cart_path(current_user.id, current_user.shopping_cart.id) %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path  %> |
            <%= link_to "Login", new_user_session_path  %>
          <% end %>
        </div>
		</div>
    </nav>
  </header>

  <div class="container">
    <%= yield %>
  </div>

  <div class="container">
  	<p class="text-center">Thank you Noun Project for the Home image</p>

  </div>
</body>
</html>

app/views/products/_product_form.html.erb
<div class="form-container">
  <%= bootstrap_form_for @product, label_errors: true, layout: :horizontal do |f| %>

    <div>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.text_area :description %>
    </div>

    <div>
      <%= f.text_field :quantity %>
    </div>

    <div>
      <%= f.text_field :price %>
    </div>



    <div class="row">
      <div class="col-lg-3 col-lg-offset-5">
        <%= f.submit class: "btn btn-info"%>
      </div>
    </div>

  <% end %>
</div>

app/views/products/admin/_product_form.html.erb
<div class="form-container">
  <%= bootstrap_form_for @product, label_errors: true, layout: :horizontal do |f| %>

    <div>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.text_area :description %>
    </div>

    <div>
      <%= f.text_field :quantity %>
    </div>

    <div>
      <%= f.text_field :price %>
    </div>



    <div class="row">
      <div class="col-lg-3 col-lg-offset-5">
        <%= f.submit class: "btn btn-info"%>
      </div>
    </div>

  <% end %>
</div>

app/views/products/admin/_products.html.erb
<div class="table-responsive">
  <% unless @products.empty? %>
  <table class="table">
    <thead>
      <tr>
        <% @products.first.attributes.keys.each do |attr| %>
          <th><%= attr %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr id="<%= dom_id(product) %>">
          <% product.attributes.each do |k, attr| %>
            <% if k == "name" %>
              <td><%= link_to(attr, product_path(product)) %></td>
            <% else %>
              <td><%= attr %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>
<div class="row">
  <div class="btn btn-success col-md-4 col-md-offset-4" id="create-btn" >
    <%= link_to("Create New Product", new_product_path) %>
  </div>
</div>

app/views/products/edit.html.erb
<!-- renders partial form -->
<%= render partial: 'products/admin/product_form'  %>

app/views/products/index.html.erb
<% if user_signed_in? && current_user.admin %>
  <%= render partial: 'products/admin/products'  %>
<% else %>
  <%= render partial: 'products/shopper/products'  %>
<% end %>

app/views/products/new.html.erb
<!-- renders partial -->
<%= render partial: 'products/admin/product_form'  %>

app/views/products/shopper/_products.html.erb
<% @products.each do |product| %>
  <%= link_to(product_path(product), class: "hover-area col-md-2 col-sm-2 col-xs-6") do %>
    <%# link_to image_tag("https://avatars1.githubusercontent.com/u/10661978?v=3&s=200", class: "hover-img img-responsive col-md-2 col-sm-2 col-xs-6"), product_path(product) %>

      <div class="hover-txt" id="<%= dom_id(product)%>">
          <span>
            <%= product.name %>
          </span>
          <div>
            $<%= product.price %>
          </div>
      </div>
  <% end %>

<% end  %>

app/views/products/show.html.erb
<div>
  <h1><%= @product.name %></h1>
    <p> Description: <%= @product.description %></p>
    <p> Price: $ <%= @product.price %> </p>
    <p> Quantity: <%= @product.quantity %></p>
</div>

<% if user_signed_in? && current_user.admin %>
  <%= link_to("Update Product Info", edit_product_path, class: "btn btn-info") %>
  <%= link_to("Delete Product", product_path, method: :delete, class: "btn btn-danger") %>
<% end %>

<% if user_signed_in? && !current_user.admin %>
  <div class="form-container">
    <%= form_for @shopping_cart, url: user_shopping_cart_path(current_user.id,current_user.shopping_cart.id), method: :put do |f| %>

      <div>
        <%= f.hidden_field :product_id, value: @product.id %>
      </div>

      <div class="row">
        <div class="col-lg-3 col-lg-offset-5">
          <%= f.submit "Add to cart", class: "btn btn-info" %>
        </div>
      </div>

    <% end %>
  </div>
<% end %>

app/views/shopping_carts/edit.html.erb
<div class="row">
	<div class="col-md-2"> Name:</div>
	<div class="col-md-1"> Price:</div>

</div>
<% @products.each do |product|%>
<div class="row">
	<div class="col-md-2"><%= product.name %></div>
	<div class="col-md-1"> <%= product.price %></div>
	<%=bootstrap_form_for @shopping_cart, url: user_shopping_cart_path(current_user.id, current_user.shopping_cart.id), method: :put  do |f|  %>
	<%= f.hidden_field :product_id, value: product.id %>
	<%=  f.hidden_field :remove, value: true  %>
	<%= f.submit "Remove", class: "btn btn-danger col-md-1" %>
	<% end %>
</div>

<% end %>
<%=link_to "clear cart", user_shopping_cart_path(current_user.id,current_user.shopping_cart.id), method: :delete, class: "btn btn-danger col-md-1"  %>

app/views/shopping_carts/show.html.erb
<% @products.each do |product|%>
<div><%= product.name %></div>
<div><%= product.price %></div>


<% end %>